### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by peter-gribanov** [Happyr/Doctrine-Specification#254]
## Major release plans

* [x] Build from GitHub CI #250, #253
* [x] Disable Style CI #252
* [x] Test CS by PHP CS Fixer #246
* [x] Declare strict types #245
* [x] Remove deprecated code #247, #249, #248, #251, #264
* [x] Declare type hinting #266
* [x] Declare strict types #245
* [x] Add support PHP 8 #259
* [x] Stop supporting older versions of PHP #259
* [x] Break BC with Doctrine ORM `2.2`, `2.3`, `2.4` #258
* [x] Break BC with PHPSpec `2.x`, `3.x`, `4.x`, `5.x`, #259
* [x] Remove `AbstractJoin::getJoinType()` method #226 #260
* [x] Remove deprecated `Bitwise` operands #249
* [x] Mark `LogicX` class as `abstract` #247
* [x] Mark `Comparison` class as `abstract` #247
* [x] Change access of `protected` properties to `private` #251
* [x] Remove `Happyr\DoctrineSpecification\Specification\Having` class #262
* [x] Use variable-length argument lists #263
* [x] Prefer composition over inheritance #268
* [x] Remove deprecated `Modulo` arithmetic operand #271
* [x] Check single entity satisfiability #273
* [x] `TRIM()` platform functions does not support options #278
* [x] Group repository classes in `Repository` folder #281
* [x] Сorrect location of `BaseSpecification` class #282
* [x] Iterate repository by specification with a real key from original query #283
* [x] Fix the `CONCAT` function declaration #284
* [x] Сhange `CountDistinct` to `Count` platform function #285
* [x] Allow use `DISTINCT` in aggregate functions #286
* [x] Сorrect annotate `$context` argument int `BaseSpecification::__construct()` #287
* [x] Add `IS EMPTY` filter #293
* [x] [NEW Operator Syntax](https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/dql-doctrine-query-language.html#new-operator-syntax) #292
* [x] Correct resolve DQL alias in context in `SelectEntity` #288
* [x] Correct use custom context #289
* [x] The context in Operands is optional and may not be specified #290
* [x] Allow use context in `Satisfiable` methods #291
* [x] Correct resolve context in `BaseSpecification` methods from `Satisfiable` interface #294
* [x] Define JOIN before using the new alias from it #295
---

If you have any ideas for a major release, you can describe them here.

**Comment by peter-gribanov** [comment]
[Released](https://github.com/Happyr/Doctrine-Specification/releases/tag/v2.0.0).
